export enum Section {
  HOME = 'HOME',
  SERVICES = 'SERVICES',
  SERVICE_DETAIL = 'SERVICE_DETAIL',
  STATE_LICENSING = 'STATE_LICENSING',
  INTERNATIONAL_MAP = 'INTERNATIONAL_MAP',
  ACADEMY = 'ACADEMY',
  DASHBOARD = 'DASHBOARD',
  MENTOR = 'MENTOR',
  OPPORTUNITY = 'OPPORTUNITY',
  UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  ADMIN_PANEL = 'ADMIN_PANEL',
  CLIENT_PANEL = 'CLIENT_PANEL',
  SHIPPER_PANEL = 'SHIPPER_PANEL',
  COURSE_PLAYER = 'COURSE_PLAYER',
  NEWS_BOARD = 'NEWS_BOARD',
  ABOUT = 'ABOUT',
  STRATEGIC_ROADMAP = 'STRATEGIC_ROADMAP',
  SOLUTION_SHOWCASE = 'SOLUTION_SHOWCASE'
}

export type UserRole = 'visitor' | 'subscriber' | 'partner' | 'admin' | 'shipper';
export type Language = 'pt' | 'en' | 'es';
